---
- hosts: all
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      update_cache: yes 
      state: latest
  - name: uploading default index.html for host
    copy: 
      src: index.html 
      dest: /var/www/html
  - name: Setting up attributes for file
    file:
      path: /var/www/html/index.html
      owner: root
      group: root
      mode:  0644
  - name: start apache2
    service: 
      name: apache2
      state: started 
